name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.opencover.xml
        directory: FUI.Tests
      
    - name: Run benchmark
      run: cd FUI.Benchmarks && dotnet run -c Release --exporters json --filter '*'
        
    - name: Store benchmark result
      uses: Happypig375/github-action-benchmark@v1
      with:
        name: Benchmark.Net Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: FUI.Benchmarks/BenchmarkDotNet.Artifacts/results/FUI.Benchmarks-report-full-compressed.json
        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false          
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        alert-threshold: '110%'
        comment-always: true
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@uxsoft'
        
    - name: Set version in project file
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: 1.${{ github.run_number }}.0
        
    - name: Publish to NuGet
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
