name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.opencover.xml
        directory: FUI.Tests
      
    - name: Run benchmark
      run: cd FUI.Benchmarks && dotnet run -c Release --exporters json --filter '*'
      
    #- name: Always-Cache
    #  uses: gerbal/always-cache@v1.0.3
    #  with:
    #    path: ./cache
    #    key: ${{ runner.os }}-benchmark
        
    - name: Store benchmark result
      uses: Happypig375/github-action-benchmark@v1
      with:
        name: Benchmark.Net Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: FUI.Benchmarks/BenchmarkDotNet.Artifacts/results/FUI.Benchmarks.Benchmark.Benchmarks-report-full-compressed.json
        # Where the previous data file is stored
        # external-data-json-path: ./cache/benchmark-data.json
        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false          
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '0%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@uxsoft'
      
